QUESTIONS_LIST = [
    "If you were a serial killer, who would you kill and what would your nickname be?",
    "What's your favorite type of kid?",
    "What's your most embarressing moment?",
    "What's your strangest sexual fantasy?",
    "What's been on your mind most lately?",
    "What have you learned today?",
    "What is your favorite book?",
    "What is your favorite movie?",
    "What's your favorite chapstick flavor?",
    "What do you think god smells like?",
    "What are you into these days?",
    "On a first date, how far do you go?",
    "If you were going to write a book, what would it be called?",
    "What would the book about your life be called?",
    "What accomplishments are you most proud of?",
    "When you were a kid, what did you want to be when you grew up?",
    "What do you do for fun?",
    "If you could meet anyone, who would it be?",
    "If you could go back in history, who would you meet?",
    "What is your spirit animal?",
    "What's one of the strangest things you've ever done?",
    "If you could learn one random skill, what would you learn?",
    "What's the first thing you notice about people?",
    "What would you torture someone for?",
    "What's the stupidest thing you've ever done?",
    "What do you think is would be one of the best steps we could take toward ending poverty around the world?",
    "What do you think we could do to best improve the education system?",
    "What are some of your favorite websites?",
    "What's the biggest turnoff in a man/woman?",
    "What's the first thing you do in the morning?",
    "If someone were to make a movie about your life, who would play you?",
    "How would you explain your basic life philosophy?",
    "If you knew you'd die tomorrow, what would you do today?",
    "KILL - FUCK - MARRY: Willow Smith, Will Smith, Jaden Smith",
    "KILL - FUCK - MARRY: Amy Poehler, Tina Fey, Kristen Wiig",
    "KILL - FUCK - MARRY: Chris Pratt, Larry David, Rosie O'Donnell",
    "KILL - FUCK - MARRY: Emma Watson, Jennifer Lawrence, Anna Kendrick",
    "KILL - FUCK - MARRY: The people currently playing with you",
    "If you had to kill one person known by the group playing, who would it be?",
    "If you were for genocide, what group would you kill?",
    "If you had to say you hated a group of people, what would that group be?",
    "What purchase have you made lately that you would describe as \"top shelf\"?",
]
