QUESTIONS_LIST = [
    "What are you thinking about?",
    "What's your favorite food?",
    "What's your favorite dessert?",
    "What have you learned today?",
    "What was your favorite subject in school?",
    "What is your favorite book?",
    "What is your favorite movie?",
    "What kind of music are you into?",
    "What's your favorite ramen flavor?",
    "What's your favorite chapstick flavor?",
    "What do you order when you get Chinese food?",
    "What do you think god smells like?",
    "What kind of kids are you into?",
    "What are you into these days?",
    "What's your dad's name?",
    "If you were going to write a book, what would you call it?",
    "If you were going to write a book, what would it be about?",
    "What's one of the scariest things you've ever done?",
    "What accomplishment are you most proud of?",
    "On a first date, how far do you go?",
    "Have you ever thought of adopting?",
    "When you were a kid, what did you want to be when you grew up?",
    "What do you do for fun?",
    "If you could visit any country in the world, where would you go?",
    "If you could meet anyone, who would it be?",
    "If someone asked you to give them a random piece of advice, what would you say?",
    "What's one of your favorite habits you have?",
    "What is some thing that makes you really happy?",
    "What is some thing that makes you really sad?",
    "What is something that terrifies you?",
    "Do you like to plan things out in detail or be spontaneous?",
    "Are you a religious person?",
    "If you could go back in history, who would you like to meet?",
    "Would you rather live in the country or in the city?",
    "What was your life like growing up?",
    "What were you like in high school?",
    "Do you have any brothers or sisters? How many?",
    "What's your favorite part about today so far?",
    "Who in your life has influenced you the most? How did they do it?",
    "What's your favorite joke?",
    "Have you ever tried sushi? (Did you like it?)",
    "Do you like spicy food?",
    "How do you like your steak cooked?",
    "Do you have a favorite number? Any particular reason why you like that number?",
    "If you were a type of animal, what would you be and why?",
    "What's one of the strangest things you've ever done?",
    "What kind of vacations do you like?",
    "What are some of your major goals in life?",
    "What are some of your smaller goals in life?",
    "What do you like least about yourself?",
    "What embarrasses you?",
    "If you could try out any job for a day, what would you like to try?",
    "What's your earliest memory?",
    "What's the best decision you ever made?",
    "Who's your best / closest friend?",
    "What do you think people think of you?",
    "What were your grades like in school?",
    "If you could learn one random skill, what would you learn?",
    "Are you an introvert or an extrovert?",
    "Have you ever taken a personality test? (How did the results turn out?)",
    "What's the first thing you notice about people?",
    "Do you think people can control their own destiny?",
    "Do you think all people are equally valuable, or do you think some people in certain situations might be more valuable than others (say, a severely retarded patient vs. a doctor who could potentially save hundreds of lives)?",
    "Do you think people are basically bad or basically good?",
    "Do you think morals are universal or relative to the beliefs, traditions, and practices of individuals or groups?",
    "Do you think God exists?",
    "Do you think any kind of afterlife exists?",
    "Do you vote? Why / Why not? If you do vote, how do you usually vote?",
    "Do you think gay people choose to be gay? Do you think straight people choose to be straight?",
    "Is torture ever a good option? If no, why not? If yes, when?",
    "Would you kill an innocent person if you thought it might mean saving a dozen other people?",
    "What's the most money you've ever given away?",
    "What's the biggest personal change you've ever made?",
    "What's the stupidest thing you've ever done?",
    "What do you think would be one of the best steps we could take toward ending poverty around the world?",
    "What do you think we could do to best improve the education system?",
    "In general, what do you think about art?",
    "What are some of your favorite websites?",
    "What's the biggest turnoff in a man/woman?",
    "What's the biggest lie you've ever told?",
    "What's something most people don't know about you?",
    "What's something you wish everyone knew about you?",
    "What are some of the first things you do in the morning?",
    "What's the worst thing that's ever happened to you?",
    "Do you cry easily?",
    "How do you feel about public speaking?",
    "Do you like to talk on the phone?",
    "How many emails do you get each week, roughly?",
    "If someone were to make a movie about your life, who would you hope would play you?",
    "What's one of your favorite questions to ask new friends or to get a conversation going?",
    "Would you ever sky dive or bungee jump?",
    "Have you ever been in a fist fight?",
    "What's the best prank you've ever pulled?",
    "What did you do on your 16th birthday?",
    "What do you think is one of the most undervalued professions right now?",
    "How would you explain your basic life philosophy?",
    "Would you rather be hated or forgotten?",
    "If you knew you would die tomorrow, would you feel cheated today?",
]
