QUESTIONS_LIST = [
    "If you were a serial killer, what your nickname be?",
    "What's your favorite type of kid?",
    "What's your strangest sexual fantasy?",
    "What's your favorite chapstick flavor?",
    "What do you think god smells like?",
    "When you were a kid, what did you want to be when you grew up?",
    "What is your spirit animal?",
    "If you could learn one random skill, what would it be?",
    "What would you torture someone for?",
    "What do you think we could do to best improve the education system?",
    "What's your personal blog called?",
    "If you knew you'd die tomorrow, what would you do today?",
    "If you had to kill one person in this room, who would it be?",
    "What purchase have you made lately that you would describe as \"top shelf\"?",
    "What's your karaoke song of choice?",
    "Which dead celebrity would you revive for a day?",
    "Where's the strangest place you've peed?",
    "Trump?",
    "What was your first thought when you woke up this morning?",
    "American Express just sent me a fraud alert because I bought ______.",
    "Who is your celebrity look alike?",
    "What is your favorite way to procrastinate at work?",
    "Sex for the first time felt just like ______.",
    "In the future, I will become a YouTube celebrity with a channel about ______.",
    "You will become infamous for ______.",
    "Which actor or actress would play you in a movie?",
    "Which celebrity would you love to grab a drink with?",
    "People think it's strange, but I always ______ in the shower!",
    "My favorite midnight snack is ______.",
    "In high school I should have ______.",
    "In high school, everyone made fun of me for ______.",
    "If you could do ______ for me, that'd be great.",
    "Oh no, you left something embarrassing at the printer. What is it?!",
    "What is the biggest regret you have involving your parents?",
    "What are your munchies of choice?",
    "The weirdest thing people ask me for advice about is ______.",
    "What is the body part your most musical with?",
    "I regret not peeing that one time before ______.",
    "I would totally be a festival bum, it it weren't for ______.",
    "What is your anti-dream job?",
    "Saturday night in by yourself. You're gonna ______."
    "Kids these days are all about ______.",
    "My directorial debut would be rated NC-17 because ______.",
    "I'd be really embarrassed if someone found the movie of ______ on my phone.",
    "In five years you'll be acquitted of charges for ______.",
    "My biopic will be titled ______.",
    "You're going to Washington to lobby for ______.",
    "What's your favorite topic at the water cooler?",
    "On Pandora, I always thumb down songs by ______.",
    "Believe it or not, one time I ______ in a movie theater.",
    "The first time I blacked out I drank ______.",
    "My show's theme song is titled ______.",
    "My face turns red when people call me ______.",
    "I thought no one was home and I was ______. Whoops! ¯\_(ツ)_/¯",
    "My street name is ______.",
    "If I were calling the shots, ______ would be heavily subsidized.",
    "If Abe Lincoln was naked in my bedroom, I would ______.",
    "If I held office, my political scandal would be ______.",
    "My headshot prop would be ______.",
    "My boss got upset when I made my interns do ______.",
    "If elected President, my first act in office would be ______.",
    "When I run for President, my campaign slogan would be ______.",
    "What is the weirdest thing you've ever eaten?",
    "I ate so much ______ I threw up.",
    "______, it does the body good!",
    "The hippest new restaurant in New York is called ______.",
    "If I was stuck on an island with one food, it would be ______.",
    "I really wish my ______ had a cupholder.",
    "I remember my first ______. It was painful.",
    "If I could go on a date with any sports figure, it would be ______.",
    "I think my body looks most like this food.",
    "I can fit 5 ______s in my mouth!",
    "At the state fair this year, the new specialty is deep fried ______.",
    "Michael Jordan is best known for being ______.",
    "The NFL's latest scandal is nicknamed ______.",
    "Lebron James is the ______ of all time.",
    "I always drink a gatorade after I ______.",
    "With the new iPhone, you can shake it to do ______.",
    "It's all fun and games until someone ______.",
    "Serena Williams has the ______.",
    "The only thing I remember from my first college part is ______."
]
